---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "RUM API SERVER"
  description: "HELLO RUM"
schemes:
- "https"
- "http"
host: "localhost:10010"
basePath: "/api/v1"

tags:
- name: "test"
  description: "test"

consumes:
- "application/json"
- "application/x-www-form-urlencoded"
- "application/octet-stream"
produces:
- "application/javascript"
- "application/json"
- "text/plain; charset=utf-8"
paths:

  /hello:
    x-swagger-router-controller: "Helloworld"
    get:
      tags:
      - "test"
      operationId: "sayhelloUsingGET"
      description: "hello"
      responses:
        200:
          description: "ok"